Version change to 0.32.0
maidsafe/crust pull request #1155
Opened 2019-05-28 14:30 UTC by lionel1704

- Update Travis script and maidsafe_utilities dependency 
- Version change to 0.32.0

2019-05-28 14:35 UTC, nbaksalyar requested changes

2019-05-28 14:35 UTC, nbaksalyar commented on .travis.yml
>    - 1.29.2
Needs to be replaced with `stable`:
```suggestion
  - stable
```

2019-05-28 15:32 UTC, mrcnski requested changes
Looks like this PR is missing some clippy fixes:
https://github.com/maidsafe/crust/compare/legacy...m-cat:legacy-clippy

2019-05-29 08:13 UTC, nbaksalyar submitted a review, later dismissed
Thanks @lionel1704 and @m-cat, good work! :+1:

2019-05-29 10:54 UTC, merged